# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 518164f556043dec10c5a7479cd7e0d0162210a15c3b43b73b1bed264cb620128866448924286b19491c59d3cdb44e7fb6bcef49b24444af80d6acef60516b32

test:
  secret_key_base: 3471c3eaf5dab1e0c62c674090b31030967526899670ce05de39ef1511447ddb7c15fa3c63503ead82aa01643dc738b6ffef4421d7698d890a4ebc442640af36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
